---

- name: Install PostgreSQL
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  register: db_setup
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

#- name: Setup postgres cluster
#  shell: pg_createcluster 9.3 main --start
#  when: db_setup.changed

- include: setup_database_default.yml

- include: setup_database_mag.yml

- include: setup_database_dblp.yml
