---

- name: Ensure dblp database is created
  sudo_user: postgres
  postgresql_db: name={{ dblp_db_name }}

- name: Ensure dblp user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ dblp_db_name }}
                   name={{ dblp_db_user }}
                   password={{ dblp_db_password }}
                   priv=ALL

- name: Ensure dblp user does not have unnecessary privileges
  sudo_user: postgres
  postgresql_user: name={{ dblp_db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB