---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - base
    - postgresql
    - rabbitmq
    - web
    - celery
    #- grobid