---

#- name: Install MySQL-python dependencies
#  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
#  with_items:
#    - libmysqlclient-dev

- name: Install lxml dependencies
  apt: pkg={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev

#- name: Install requests dependencies
#  apt: pkg={{ item }} update_cache={{ update_apt_cache }} state=installed
#  with_items:
#    - libffi-dev
